### ISSUE TITLE
Fix aiohttp client

### ISSUE THREAD

**Issue by ephes** [ephes/will_it_saturate#3]
```python
ERROR:    Exception in ASGI application
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 5001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/clients.py", line 189, in measure_in_new_process
    elapsed, responses = asyncio.run(self.measure_server(epoch))
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/clients.py", line 184, in measure_server
    responses = await asyncio.gather(*tasks)
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/clients.py", line 168, in fetch_page
    async with session.get(url) as response:
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5001 ssl:default [Connect call failed ('127.0.0.1', 5001)]
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/control/main.py", line 85, in measure
    return benchmark_client.measure(epoch)
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/clients.py", line 197, in measure
    [result, timestamps] = p.map(self.measure_in_new_process, [epoch])
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/jochen/.pyenv/versions/3.10.4/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5001 ssl:default [Connect call failed ('127.0.0.1', 5001)]
```

**Comment by ephes** [comment]
This is the correct traceback:
```python
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/jochen/.virtualenvs/wis/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/control/main.py", line 85, in measure
    return benchmark_client.measure(epoch)
  File "/Users/jochen/projects/will_it_saturate/will_it_saturate/clients.py", line 197, in measure
    [result, timestamps] = p.map(self.measure_in_new_process, [epoch])
ValueError: not enough values to unpack (expected 2, got 1)
```
